
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Session: 'Session',
  Player: 'Player',
  Court: 'Court',
  Transaction_Random: 'Transaction_Random'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const SessionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  startAt: 'startAt',
  location: 'location',
  playerCount: 'playerCount',
  courtCount: 'courtCount',
  roomCode: 'roomCode',
  amountPerGame: 'amountPerGame',
  createdDate: 'createdDate',
  createdBy: 'createdBy',
  updatedDate: 'updatedDate',
  updatedBy: 'updatedBy',
  isActive: 'isActive',
  isRandom: 'isRandom'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const PlayerScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  name: 'name',
  level: 'level',
  isOnline: 'isOnline',
  isPaid: 'isPaid',
  isActive: 'isActive',
  isPlaying: 'isPlaying',
  playingSince: 'playingSince',
  createdDate: 'createdDate',
  createdBy: 'createdBy',
  updatedDate: 'updatedDate',
  updatedBy: 'updatedBy'
} as const

export type PlayerScalarFieldEnum = (typeof PlayerScalarFieldEnum)[keyof typeof PlayerScalarFieldEnum]


export const CourtScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  no: 'no',
  name: 'name',
  isAvailable: 'isAvailable',
  isDeleted: 'isDeleted',
  createdDate: 'createdDate',
  createdBy: 'createdBy',
  updatedDate: 'updatedDate',
  updatedBy: 'updatedBy'
} as const

export type CourtScalarFieldEnum = (typeof CourtScalarFieldEnum)[keyof typeof CourtScalarFieldEnum]


export const Transaction_RandomScalarFieldEnum = {
  id: 'id',
  courtId: 'courtId',
  playerId_A1: 'playerId_A1',
  playerId_A2: 'playerId_A2',
  playerId_B3: 'playerId_B3',
  playerId_B4: 'playerId_B4',
  sessionId: 'sessionId',
  isEndGame: 'isEndGame',
  isTemp: 'isTemp',
  createdDate: 'createdDate',
  createdBy: 'createdBy',
  updatedDate: 'updatedDate',
  updatedBy: 'updatedBy'
} as const

export type Transaction_RandomScalarFieldEnum = (typeof Transaction_RandomScalarFieldEnum)[keyof typeof Transaction_RandomScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

