
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Player` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Player
 * 
 */
export type PlayerModel = runtime.Types.Result.DefaultSelection<Prisma.$PlayerPayload>

export type AggregatePlayer = {
  _count: PlayerCountAggregateOutputType | null
  _min: PlayerMinAggregateOutputType | null
  _max: PlayerMaxAggregateOutputType | null
}

export type PlayerMinAggregateOutputType = {
  id: string | null
  sessionId: string | null
  name: string | null
  level: string | null
  isOnline: boolean | null
  isPaid: boolean | null
  isActive: boolean | null
  isPlaying: boolean | null
  playingSince: Date | null
  createdDate: Date | null
  createdBy: string | null
  updatedDate: Date | null
  updatedBy: string | null
}

export type PlayerMaxAggregateOutputType = {
  id: string | null
  sessionId: string | null
  name: string | null
  level: string | null
  isOnline: boolean | null
  isPaid: boolean | null
  isActive: boolean | null
  isPlaying: boolean | null
  playingSince: Date | null
  createdDate: Date | null
  createdBy: string | null
  updatedDate: Date | null
  updatedBy: string | null
}

export type PlayerCountAggregateOutputType = {
  id: number
  sessionId: number
  name: number
  level: number
  isOnline: number
  isPaid: number
  isActive: number
  isPlaying: number
  playingSince: number
  createdDate: number
  createdBy: number
  updatedDate: number
  updatedBy: number
  _all: number
}


export type PlayerMinAggregateInputType = {
  id?: true
  sessionId?: true
  name?: true
  level?: true
  isOnline?: true
  isPaid?: true
  isActive?: true
  isPlaying?: true
  playingSince?: true
  createdDate?: true
  createdBy?: true
  updatedDate?: true
  updatedBy?: true
}

export type PlayerMaxAggregateInputType = {
  id?: true
  sessionId?: true
  name?: true
  level?: true
  isOnline?: true
  isPaid?: true
  isActive?: true
  isPlaying?: true
  playingSince?: true
  createdDate?: true
  createdBy?: true
  updatedDate?: true
  updatedBy?: true
}

export type PlayerCountAggregateInputType = {
  id?: true
  sessionId?: true
  name?: true
  level?: true
  isOnline?: true
  isPaid?: true
  isActive?: true
  isPlaying?: true
  playingSince?: true
  createdDate?: true
  createdBy?: true
  updatedDate?: true
  updatedBy?: true
  _all?: true
}

export type PlayerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Player to aggregate.
   */
  where?: Prisma.PlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Players to fetch.
   */
  orderBy?: Prisma.PlayerOrderByWithRelationInput | Prisma.PlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Players from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Players.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Players
  **/
  _count?: true | PlayerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlayerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlayerMaxAggregateInputType
}

export type GetPlayerAggregateType<T extends PlayerAggregateArgs> = {
      [P in keyof T & keyof AggregatePlayer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlayer[P]>
    : Prisma.GetScalarType<T[P], AggregatePlayer[P]>
}




export type PlayerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlayerWhereInput
  orderBy?: Prisma.PlayerOrderByWithAggregationInput | Prisma.PlayerOrderByWithAggregationInput[]
  by: Prisma.PlayerScalarFieldEnum[] | Prisma.PlayerScalarFieldEnum
  having?: Prisma.PlayerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlayerCountAggregateInputType | true
  _min?: PlayerMinAggregateInputType
  _max?: PlayerMaxAggregateInputType
}

export type PlayerGroupByOutputType = {
  id: string
  sessionId: string
  name: string
  level: string
  isOnline: boolean
  isPaid: boolean
  isActive: boolean
  isPlaying: boolean
  playingSince: Date | null
  createdDate: Date
  createdBy: string
  updatedDate: Date
  updatedBy: string
  _count: PlayerCountAggregateOutputType | null
  _min: PlayerMinAggregateOutputType | null
  _max: PlayerMaxAggregateOutputType | null
}

type GetPlayerGroupByPayload<T extends PlayerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlayerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlayerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlayerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlayerGroupByOutputType[P]>
      }
    >
  >



export type PlayerWhereInput = {
  AND?: Prisma.PlayerWhereInput | Prisma.PlayerWhereInput[]
  OR?: Prisma.PlayerWhereInput[]
  NOT?: Prisma.PlayerWhereInput | Prisma.PlayerWhereInput[]
  id?: Prisma.UuidFilter<"Player"> | string
  sessionId?: Prisma.UuidFilter<"Player"> | string
  name?: Prisma.StringFilter<"Player"> | string
  level?: Prisma.StringFilter<"Player"> | string
  isOnline?: Prisma.BoolFilter<"Player"> | boolean
  isPaid?: Prisma.BoolFilter<"Player"> | boolean
  isActive?: Prisma.BoolFilter<"Player"> | boolean
  isPlaying?: Prisma.BoolFilter<"Player"> | boolean
  playingSince?: Prisma.DateTimeNullableFilter<"Player"> | Date | string | null
  createdDate?: Prisma.DateTimeFilter<"Player"> | Date | string
  createdBy?: Prisma.UuidFilter<"Player"> | string
  updatedDate?: Prisma.DateTimeFilter<"Player"> | Date | string
  updatedBy?: Prisma.UuidFilter<"Player"> | string
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  randomAsP1?: Prisma.Transaction_RandomListRelationFilter
  randomAsP2?: Prisma.Transaction_RandomListRelationFilter
  randomAsP3?: Prisma.Transaction_RandomListRelationFilter
  randomAsP4?: Prisma.Transaction_RandomListRelationFilter
}

export type PlayerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  isPaid?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isPlaying?: Prisma.SortOrder
  playingSince?: Prisma.SortOrderInput | Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  session?: Prisma.SessionOrderByWithRelationInput
  randomAsP1?: Prisma.Transaction_RandomOrderByRelationAggregateInput
  randomAsP2?: Prisma.Transaction_RandomOrderByRelationAggregateInput
  randomAsP3?: Prisma.Transaction_RandomOrderByRelationAggregateInput
  randomAsP4?: Prisma.Transaction_RandomOrderByRelationAggregateInput
}

export type PlayerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PlayerWhereInput | Prisma.PlayerWhereInput[]
  OR?: Prisma.PlayerWhereInput[]
  NOT?: Prisma.PlayerWhereInput | Prisma.PlayerWhereInput[]
  sessionId?: Prisma.UuidFilter<"Player"> | string
  name?: Prisma.StringFilter<"Player"> | string
  level?: Prisma.StringFilter<"Player"> | string
  isOnline?: Prisma.BoolFilter<"Player"> | boolean
  isPaid?: Prisma.BoolFilter<"Player"> | boolean
  isActive?: Prisma.BoolFilter<"Player"> | boolean
  isPlaying?: Prisma.BoolFilter<"Player"> | boolean
  playingSince?: Prisma.DateTimeNullableFilter<"Player"> | Date | string | null
  createdDate?: Prisma.DateTimeFilter<"Player"> | Date | string
  createdBy?: Prisma.UuidFilter<"Player"> | string
  updatedDate?: Prisma.DateTimeFilter<"Player"> | Date | string
  updatedBy?: Prisma.UuidFilter<"Player"> | string
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  randomAsP1?: Prisma.Transaction_RandomListRelationFilter
  randomAsP2?: Prisma.Transaction_RandomListRelationFilter
  randomAsP3?: Prisma.Transaction_RandomListRelationFilter
  randomAsP4?: Prisma.Transaction_RandomListRelationFilter
}, "id">

export type PlayerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  isPaid?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isPlaying?: Prisma.SortOrder
  playingSince?: Prisma.SortOrderInput | Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  _count?: Prisma.PlayerCountOrderByAggregateInput
  _max?: Prisma.PlayerMaxOrderByAggregateInput
  _min?: Prisma.PlayerMinOrderByAggregateInput
}

export type PlayerScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlayerScalarWhereWithAggregatesInput | Prisma.PlayerScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlayerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlayerScalarWhereWithAggregatesInput | Prisma.PlayerScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Player"> | string
  sessionId?: Prisma.UuidWithAggregatesFilter<"Player"> | string
  name?: Prisma.StringWithAggregatesFilter<"Player"> | string
  level?: Prisma.StringWithAggregatesFilter<"Player"> | string
  isOnline?: Prisma.BoolWithAggregatesFilter<"Player"> | boolean
  isPaid?: Prisma.BoolWithAggregatesFilter<"Player"> | boolean
  isActive?: Prisma.BoolWithAggregatesFilter<"Player"> | boolean
  isPlaying?: Prisma.BoolWithAggregatesFilter<"Player"> | boolean
  playingSince?: Prisma.DateTimeNullableWithAggregatesFilter<"Player"> | Date | string | null
  createdDate?: Prisma.DateTimeWithAggregatesFilter<"Player"> | Date | string
  createdBy?: Prisma.UuidWithAggregatesFilter<"Player"> | string
  updatedDate?: Prisma.DateTimeWithAggregatesFilter<"Player"> | Date | string
  updatedBy?: Prisma.UuidWithAggregatesFilter<"Player"> | string
}

export type PlayerCreateInput = {
  id?: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  session: Prisma.SessionCreateNestedOneWithoutPlayersInput
  randomAsP1?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer1Input
  randomAsP2?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer2Input
  randomAsP3?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer3Input
  randomAsP4?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer4Input
}

export type PlayerUncheckedCreateInput = {
  id?: string
  sessionId: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  randomAsP1?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer1Input
  randomAsP2?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer2Input
  randomAsP3?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer3Input
  randomAsP4?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer4Input
}

export type PlayerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  session?: Prisma.SessionUpdateOneRequiredWithoutPlayersNestedInput
  randomAsP1?: Prisma.Transaction_RandomUpdateManyWithoutPlayer1NestedInput
  randomAsP2?: Prisma.Transaction_RandomUpdateManyWithoutPlayer2NestedInput
  randomAsP3?: Prisma.Transaction_RandomUpdateManyWithoutPlayer3NestedInput
  randomAsP4?: Prisma.Transaction_RandomUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  randomAsP1?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer1NestedInput
  randomAsP2?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer2NestedInput
  randomAsP3?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer3NestedInput
  randomAsP4?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer4NestedInput
}

export type PlayerCreateManyInput = {
  id?: string
  sessionId: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
}

export type PlayerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PlayerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PlayerListRelationFilter = {
  every?: Prisma.PlayerWhereInput
  some?: Prisma.PlayerWhereInput
  none?: Prisma.PlayerWhereInput
}

export type PlayerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PlayerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  isPaid?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isPlaying?: Prisma.SortOrder
  playingSince?: Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
}

export type PlayerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  isPaid?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isPlaying?: Prisma.SortOrder
  playingSince?: Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
}

export type PlayerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  level?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  isPaid?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isPlaying?: Prisma.SortOrder
  playingSince?: Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
}

export type PlayerScalarRelationFilter = {
  is?: Prisma.PlayerWhereInput
  isNot?: Prisma.PlayerWhereInput
}

export type PlayerCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutSessionInput, Prisma.PlayerUncheckedCreateWithoutSessionInput> | Prisma.PlayerCreateWithoutSessionInput[] | Prisma.PlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutSessionInput | Prisma.PlayerCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.PlayerCreateManySessionInputEnvelope
  connect?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
}

export type PlayerUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutSessionInput, Prisma.PlayerUncheckedCreateWithoutSessionInput> | Prisma.PlayerCreateWithoutSessionInput[] | Prisma.PlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutSessionInput | Prisma.PlayerCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.PlayerCreateManySessionInputEnvelope
  connect?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
}

export type PlayerUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutSessionInput, Prisma.PlayerUncheckedCreateWithoutSessionInput> | Prisma.PlayerCreateWithoutSessionInput[] | Prisma.PlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutSessionInput | Prisma.PlayerCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.PlayerUpsertWithWhereUniqueWithoutSessionInput | Prisma.PlayerUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.PlayerCreateManySessionInputEnvelope
  set?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
  disconnect?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
  delete?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
  connect?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
  update?: Prisma.PlayerUpdateWithWhereUniqueWithoutSessionInput | Prisma.PlayerUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.PlayerUpdateManyWithWhereWithoutSessionInput | Prisma.PlayerUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.PlayerScalarWhereInput | Prisma.PlayerScalarWhereInput[]
}

export type PlayerUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutSessionInput, Prisma.PlayerUncheckedCreateWithoutSessionInput> | Prisma.PlayerCreateWithoutSessionInput[] | Prisma.PlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutSessionInput | Prisma.PlayerCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.PlayerUpsertWithWhereUniqueWithoutSessionInput | Prisma.PlayerUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.PlayerCreateManySessionInputEnvelope
  set?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
  disconnect?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
  delete?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
  connect?: Prisma.PlayerWhereUniqueInput | Prisma.PlayerWhereUniqueInput[]
  update?: Prisma.PlayerUpdateWithWhereUniqueWithoutSessionInput | Prisma.PlayerUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.PlayerUpdateManyWithWhereWithoutSessionInput | Prisma.PlayerUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.PlayerScalarWhereInput | Prisma.PlayerScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type PlayerCreateNestedOneWithoutRandomAsP1Input = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP1Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP1Input>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRandomAsP1Input
  connect?: Prisma.PlayerWhereUniqueInput
}

export type PlayerCreateNestedOneWithoutRandomAsP2Input = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP2Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP2Input>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRandomAsP2Input
  connect?: Prisma.PlayerWhereUniqueInput
}

export type PlayerCreateNestedOneWithoutRandomAsP3Input = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP3Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP3Input>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRandomAsP3Input
  connect?: Prisma.PlayerWhereUniqueInput
}

export type PlayerCreateNestedOneWithoutRandomAsP4Input = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP4Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP4Input>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRandomAsP4Input
  connect?: Prisma.PlayerWhereUniqueInput
}

export type PlayerUpdateOneRequiredWithoutRandomAsP1NestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP1Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP1Input>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRandomAsP1Input
  upsert?: Prisma.PlayerUpsertWithoutRandomAsP1Input
  connect?: Prisma.PlayerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlayerUpdateToOneWithWhereWithoutRandomAsP1Input, Prisma.PlayerUpdateWithoutRandomAsP1Input>, Prisma.PlayerUncheckedUpdateWithoutRandomAsP1Input>
}

export type PlayerUpdateOneRequiredWithoutRandomAsP2NestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP2Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP2Input>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRandomAsP2Input
  upsert?: Prisma.PlayerUpsertWithoutRandomAsP2Input
  connect?: Prisma.PlayerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlayerUpdateToOneWithWhereWithoutRandomAsP2Input, Prisma.PlayerUpdateWithoutRandomAsP2Input>, Prisma.PlayerUncheckedUpdateWithoutRandomAsP2Input>
}

export type PlayerUpdateOneRequiredWithoutRandomAsP3NestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP3Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP3Input>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRandomAsP3Input
  upsert?: Prisma.PlayerUpsertWithoutRandomAsP3Input
  connect?: Prisma.PlayerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlayerUpdateToOneWithWhereWithoutRandomAsP3Input, Prisma.PlayerUpdateWithoutRandomAsP3Input>, Prisma.PlayerUncheckedUpdateWithoutRandomAsP3Input>
}

export type PlayerUpdateOneRequiredWithoutRandomAsP4NestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP4Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP4Input>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRandomAsP4Input
  upsert?: Prisma.PlayerUpsertWithoutRandomAsP4Input
  connect?: Prisma.PlayerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlayerUpdateToOneWithWhereWithoutRandomAsP4Input, Prisma.PlayerUpdateWithoutRandomAsP4Input>, Prisma.PlayerUncheckedUpdateWithoutRandomAsP4Input>
}

export type PlayerCreateWithoutSessionInput = {
  id?: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  randomAsP1?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer1Input
  randomAsP2?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer2Input
  randomAsP3?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer3Input
  randomAsP4?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer4Input
}

export type PlayerUncheckedCreateWithoutSessionInput = {
  id?: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  randomAsP1?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer1Input
  randomAsP2?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer2Input
  randomAsP3?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer3Input
  randomAsP4?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer4Input
}

export type PlayerCreateOrConnectWithoutSessionInput = {
  where: Prisma.PlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerCreateWithoutSessionInput, Prisma.PlayerUncheckedCreateWithoutSessionInput>
}

export type PlayerCreateManySessionInputEnvelope = {
  data: Prisma.PlayerCreateManySessionInput | Prisma.PlayerCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type PlayerUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.PlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.PlayerUpdateWithoutSessionInput, Prisma.PlayerUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.PlayerCreateWithoutSessionInput, Prisma.PlayerUncheckedCreateWithoutSessionInput>
}

export type PlayerUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.PlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.PlayerUpdateWithoutSessionInput, Prisma.PlayerUncheckedUpdateWithoutSessionInput>
}

export type PlayerUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.PlayerScalarWhereInput
  data: Prisma.XOR<Prisma.PlayerUpdateManyMutationInput, Prisma.PlayerUncheckedUpdateManyWithoutSessionInput>
}

export type PlayerScalarWhereInput = {
  AND?: Prisma.PlayerScalarWhereInput | Prisma.PlayerScalarWhereInput[]
  OR?: Prisma.PlayerScalarWhereInput[]
  NOT?: Prisma.PlayerScalarWhereInput | Prisma.PlayerScalarWhereInput[]
  id?: Prisma.UuidFilter<"Player"> | string
  sessionId?: Prisma.UuidFilter<"Player"> | string
  name?: Prisma.StringFilter<"Player"> | string
  level?: Prisma.StringFilter<"Player"> | string
  isOnline?: Prisma.BoolFilter<"Player"> | boolean
  isPaid?: Prisma.BoolFilter<"Player"> | boolean
  isActive?: Prisma.BoolFilter<"Player"> | boolean
  isPlaying?: Prisma.BoolFilter<"Player"> | boolean
  playingSince?: Prisma.DateTimeNullableFilter<"Player"> | Date | string | null
  createdDate?: Prisma.DateTimeFilter<"Player"> | Date | string
  createdBy?: Prisma.UuidFilter<"Player"> | string
  updatedDate?: Prisma.DateTimeFilter<"Player"> | Date | string
  updatedBy?: Prisma.UuidFilter<"Player"> | string
}

export type PlayerCreateWithoutRandomAsP1Input = {
  id?: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  session: Prisma.SessionCreateNestedOneWithoutPlayersInput
  randomAsP2?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer2Input
  randomAsP3?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer3Input
  randomAsP4?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer4Input
}

export type PlayerUncheckedCreateWithoutRandomAsP1Input = {
  id?: string
  sessionId: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  randomAsP2?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer2Input
  randomAsP3?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer3Input
  randomAsP4?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer4Input
}

export type PlayerCreateOrConnectWithoutRandomAsP1Input = {
  where: Prisma.PlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP1Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP1Input>
}

export type PlayerCreateWithoutRandomAsP2Input = {
  id?: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  session: Prisma.SessionCreateNestedOneWithoutPlayersInput
  randomAsP1?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer1Input
  randomAsP3?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer3Input
  randomAsP4?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer4Input
}

export type PlayerUncheckedCreateWithoutRandomAsP2Input = {
  id?: string
  sessionId: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  randomAsP1?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer1Input
  randomAsP3?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer3Input
  randomAsP4?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer4Input
}

export type PlayerCreateOrConnectWithoutRandomAsP2Input = {
  where: Prisma.PlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP2Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP2Input>
}

export type PlayerCreateWithoutRandomAsP3Input = {
  id?: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  session: Prisma.SessionCreateNestedOneWithoutPlayersInput
  randomAsP1?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer1Input
  randomAsP2?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer2Input
  randomAsP4?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer4Input
}

export type PlayerUncheckedCreateWithoutRandomAsP3Input = {
  id?: string
  sessionId: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  randomAsP1?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer1Input
  randomAsP2?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer2Input
  randomAsP4?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer4Input
}

export type PlayerCreateOrConnectWithoutRandomAsP3Input = {
  where: Prisma.PlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP3Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP3Input>
}

export type PlayerCreateWithoutRandomAsP4Input = {
  id?: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  session: Prisma.SessionCreateNestedOneWithoutPlayersInput
  randomAsP1?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer1Input
  randomAsP2?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer2Input
  randomAsP3?: Prisma.Transaction_RandomCreateNestedManyWithoutPlayer3Input
}

export type PlayerUncheckedCreateWithoutRandomAsP4Input = {
  id?: string
  sessionId: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
  randomAsP1?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer1Input
  randomAsP2?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer2Input
  randomAsP3?: Prisma.Transaction_RandomUncheckedCreateNestedManyWithoutPlayer3Input
}

export type PlayerCreateOrConnectWithoutRandomAsP4Input = {
  where: Prisma.PlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP4Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP4Input>
}

export type PlayerUpsertWithoutRandomAsP1Input = {
  update: Prisma.XOR<Prisma.PlayerUpdateWithoutRandomAsP1Input, Prisma.PlayerUncheckedUpdateWithoutRandomAsP1Input>
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP1Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP1Input>
  where?: Prisma.PlayerWhereInput
}

export type PlayerUpdateToOneWithWhereWithoutRandomAsP1Input = {
  where?: Prisma.PlayerWhereInput
  data: Prisma.XOR<Prisma.PlayerUpdateWithoutRandomAsP1Input, Prisma.PlayerUncheckedUpdateWithoutRandomAsP1Input>
}

export type PlayerUpdateWithoutRandomAsP1Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  session?: Prisma.SessionUpdateOneRequiredWithoutPlayersNestedInput
  randomAsP2?: Prisma.Transaction_RandomUpdateManyWithoutPlayer2NestedInput
  randomAsP3?: Prisma.Transaction_RandomUpdateManyWithoutPlayer3NestedInput
  randomAsP4?: Prisma.Transaction_RandomUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUncheckedUpdateWithoutRandomAsP1Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  randomAsP2?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer2NestedInput
  randomAsP3?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer3NestedInput
  randomAsP4?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUpsertWithoutRandomAsP2Input = {
  update: Prisma.XOR<Prisma.PlayerUpdateWithoutRandomAsP2Input, Prisma.PlayerUncheckedUpdateWithoutRandomAsP2Input>
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP2Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP2Input>
  where?: Prisma.PlayerWhereInput
}

export type PlayerUpdateToOneWithWhereWithoutRandomAsP2Input = {
  where?: Prisma.PlayerWhereInput
  data: Prisma.XOR<Prisma.PlayerUpdateWithoutRandomAsP2Input, Prisma.PlayerUncheckedUpdateWithoutRandomAsP2Input>
}

export type PlayerUpdateWithoutRandomAsP2Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  session?: Prisma.SessionUpdateOneRequiredWithoutPlayersNestedInput
  randomAsP1?: Prisma.Transaction_RandomUpdateManyWithoutPlayer1NestedInput
  randomAsP3?: Prisma.Transaction_RandomUpdateManyWithoutPlayer3NestedInput
  randomAsP4?: Prisma.Transaction_RandomUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUncheckedUpdateWithoutRandomAsP2Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  randomAsP1?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer1NestedInput
  randomAsP3?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer3NestedInput
  randomAsP4?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUpsertWithoutRandomAsP3Input = {
  update: Prisma.XOR<Prisma.PlayerUpdateWithoutRandomAsP3Input, Prisma.PlayerUncheckedUpdateWithoutRandomAsP3Input>
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP3Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP3Input>
  where?: Prisma.PlayerWhereInput
}

export type PlayerUpdateToOneWithWhereWithoutRandomAsP3Input = {
  where?: Prisma.PlayerWhereInput
  data: Prisma.XOR<Prisma.PlayerUpdateWithoutRandomAsP3Input, Prisma.PlayerUncheckedUpdateWithoutRandomAsP3Input>
}

export type PlayerUpdateWithoutRandomAsP3Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  session?: Prisma.SessionUpdateOneRequiredWithoutPlayersNestedInput
  randomAsP1?: Prisma.Transaction_RandomUpdateManyWithoutPlayer1NestedInput
  randomAsP2?: Prisma.Transaction_RandomUpdateManyWithoutPlayer2NestedInput
  randomAsP4?: Prisma.Transaction_RandomUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUncheckedUpdateWithoutRandomAsP3Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  randomAsP1?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer1NestedInput
  randomAsP2?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer2NestedInput
  randomAsP4?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUpsertWithoutRandomAsP4Input = {
  update: Prisma.XOR<Prisma.PlayerUpdateWithoutRandomAsP4Input, Prisma.PlayerUncheckedUpdateWithoutRandomAsP4Input>
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRandomAsP4Input, Prisma.PlayerUncheckedCreateWithoutRandomAsP4Input>
  where?: Prisma.PlayerWhereInput
}

export type PlayerUpdateToOneWithWhereWithoutRandomAsP4Input = {
  where?: Prisma.PlayerWhereInput
  data: Prisma.XOR<Prisma.PlayerUpdateWithoutRandomAsP4Input, Prisma.PlayerUncheckedUpdateWithoutRandomAsP4Input>
}

export type PlayerUpdateWithoutRandomAsP4Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  session?: Prisma.SessionUpdateOneRequiredWithoutPlayersNestedInput
  randomAsP1?: Prisma.Transaction_RandomUpdateManyWithoutPlayer1NestedInput
  randomAsP2?: Prisma.Transaction_RandomUpdateManyWithoutPlayer2NestedInput
  randomAsP3?: Prisma.Transaction_RandomUpdateManyWithoutPlayer3NestedInput
}

export type PlayerUncheckedUpdateWithoutRandomAsP4Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  randomAsP1?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer1NestedInput
  randomAsP2?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer2NestedInput
  randomAsP3?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer3NestedInput
}

export type PlayerCreateManySessionInput = {
  id?: string
  name: string
  level: string
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: Date | string | null
  createdDate?: Date | string
  createdBy: string
  updatedDate?: Date | string
  updatedBy: string
}

export type PlayerUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  randomAsP1?: Prisma.Transaction_RandomUpdateManyWithoutPlayer1NestedInput
  randomAsP2?: Prisma.Transaction_RandomUpdateManyWithoutPlayer2NestedInput
  randomAsP3?: Prisma.Transaction_RandomUpdateManyWithoutPlayer3NestedInput
  randomAsP4?: Prisma.Transaction_RandomUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
  randomAsP1?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer1NestedInput
  randomAsP2?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer2NestedInput
  randomAsP3?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer3NestedInput
  randomAsP4?: Prisma.Transaction_RandomUncheckedUpdateManyWithoutPlayer4NestedInput
}

export type PlayerUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPaid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPlaying?: Prisma.BoolFieldUpdateOperationsInput | boolean
  playingSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type PlayerCountOutputType
 */

export type PlayerCountOutputType = {
  randomAsP1: number
  randomAsP2: number
  randomAsP3: number
  randomAsP4: number
}

export type PlayerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  randomAsP1?: boolean | PlayerCountOutputTypeCountRandomAsP1Args
  randomAsP2?: boolean | PlayerCountOutputTypeCountRandomAsP2Args
  randomAsP3?: boolean | PlayerCountOutputTypeCountRandomAsP3Args
  randomAsP4?: boolean | PlayerCountOutputTypeCountRandomAsP4Args
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerCountOutputType
   */
  select?: Prisma.PlayerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeCountRandomAsP1Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Transaction_RandomWhereInput
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeCountRandomAsP2Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Transaction_RandomWhereInput
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeCountRandomAsP3Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Transaction_RandomWhereInput
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeCountRandomAsP4Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Transaction_RandomWhereInput
}


export type PlayerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  name?: boolean
  level?: boolean
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: boolean
  createdDate?: boolean
  createdBy?: boolean
  updatedDate?: boolean
  updatedBy?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  randomAsP1?: boolean | Prisma.Player$randomAsP1Args<ExtArgs>
  randomAsP2?: boolean | Prisma.Player$randomAsP2Args<ExtArgs>
  randomAsP3?: boolean | Prisma.Player$randomAsP3Args<ExtArgs>
  randomAsP4?: boolean | Prisma.Player$randomAsP4Args<ExtArgs>
  _count?: boolean | Prisma.PlayerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["player"]>

export type PlayerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  name?: boolean
  level?: boolean
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: boolean
  createdDate?: boolean
  createdBy?: boolean
  updatedDate?: boolean
  updatedBy?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["player"]>

export type PlayerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  name?: boolean
  level?: boolean
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: boolean
  createdDate?: boolean
  createdBy?: boolean
  updatedDate?: boolean
  updatedBy?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["player"]>

export type PlayerSelectScalar = {
  id?: boolean
  sessionId?: boolean
  name?: boolean
  level?: boolean
  isOnline?: boolean
  isPaid?: boolean
  isActive?: boolean
  isPlaying?: boolean
  playingSince?: boolean
  createdDate?: boolean
  createdBy?: boolean
  updatedDate?: boolean
  updatedBy?: boolean
}

export type PlayerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "name" | "level" | "isOnline" | "isPaid" | "isActive" | "isPlaying" | "playingSince" | "createdDate" | "createdBy" | "updatedDate" | "updatedBy", ExtArgs["result"]["player"]>
export type PlayerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  randomAsP1?: boolean | Prisma.Player$randomAsP1Args<ExtArgs>
  randomAsP2?: boolean | Prisma.Player$randomAsP2Args<ExtArgs>
  randomAsP3?: boolean | Prisma.Player$randomAsP3Args<ExtArgs>
  randomAsP4?: boolean | Prisma.Player$randomAsP4Args<ExtArgs>
  _count?: boolean | Prisma.PlayerCountOutputTypeDefaultArgs<ExtArgs>
}
export type PlayerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}
export type PlayerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}

export type $PlayerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Player"
  objects: {
    session: Prisma.$SessionPayload<ExtArgs>
    randomAsP1: Prisma.$Transaction_RandomPayload<ExtArgs>[]
    randomAsP2: Prisma.$Transaction_RandomPayload<ExtArgs>[]
    randomAsP3: Prisma.$Transaction_RandomPayload<ExtArgs>[]
    randomAsP4: Prisma.$Transaction_RandomPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sessionId: string
    name: string
    level: string
    isOnline: boolean
    isPaid: boolean
    isActive: boolean
    isPlaying: boolean
    playingSince: Date | null
    createdDate: Date
    createdBy: string
    updatedDate: Date
    updatedBy: string
  }, ExtArgs["result"]["player"]>
  composites: {}
}

export type PlayerGetPayload<S extends boolean | null | undefined | PlayerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlayerPayload, S>

export type PlayerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlayerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlayerCountAggregateInputType | true
  }

export interface PlayerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Player'], meta: { name: 'Player' } }
  /**
   * Find zero or one Player that matches the filter.
   * @param {PlayerFindUniqueArgs} args - Arguments to find a Player
   * @example
   * // Get one Player
   * const player = await prisma.player.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlayerFindUniqueArgs>(args: Prisma.SelectSubset<T, PlayerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Player that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlayerFindUniqueOrThrowArgs} args - Arguments to find a Player
   * @example
   * // Get one Player
   * const player = await prisma.player.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlayerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlayerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Player that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerFindFirstArgs} args - Arguments to find a Player
   * @example
   * // Get one Player
   * const player = await prisma.player.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlayerFindFirstArgs>(args?: Prisma.SelectSubset<T, PlayerFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Player that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerFindFirstOrThrowArgs} args - Arguments to find a Player
   * @example
   * // Get one Player
   * const player = await prisma.player.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlayerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlayerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Players that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Players
   * const players = await prisma.player.findMany()
   * 
   * // Get first 10 Players
   * const players = await prisma.player.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const playerWithIdOnly = await prisma.player.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlayerFindManyArgs>(args?: Prisma.SelectSubset<T, PlayerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Player.
   * @param {PlayerCreateArgs} args - Arguments to create a Player.
   * @example
   * // Create one Player
   * const Player = await prisma.player.create({
   *   data: {
   *     // ... data to create a Player
   *   }
   * })
   * 
   */
  create<T extends PlayerCreateArgs>(args: Prisma.SelectSubset<T, PlayerCreateArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Players.
   * @param {PlayerCreateManyArgs} args - Arguments to create many Players.
   * @example
   * // Create many Players
   * const player = await prisma.player.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlayerCreateManyArgs>(args?: Prisma.SelectSubset<T, PlayerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Players and returns the data saved in the database.
   * @param {PlayerCreateManyAndReturnArgs} args - Arguments to create many Players.
   * @example
   * // Create many Players
   * const player = await prisma.player.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Players and only return the `id`
   * const playerWithIdOnly = await prisma.player.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlayerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlayerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Player.
   * @param {PlayerDeleteArgs} args - Arguments to delete one Player.
   * @example
   * // Delete one Player
   * const Player = await prisma.player.delete({
   *   where: {
   *     // ... filter to delete one Player
   *   }
   * })
   * 
   */
  delete<T extends PlayerDeleteArgs>(args: Prisma.SelectSubset<T, PlayerDeleteArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Player.
   * @param {PlayerUpdateArgs} args - Arguments to update one Player.
   * @example
   * // Update one Player
   * const player = await prisma.player.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlayerUpdateArgs>(args: Prisma.SelectSubset<T, PlayerUpdateArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Players.
   * @param {PlayerDeleteManyArgs} args - Arguments to filter Players to delete.
   * @example
   * // Delete a few Players
   * const { count } = await prisma.player.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlayerDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlayerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Players.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Players
   * const player = await prisma.player.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlayerUpdateManyArgs>(args: Prisma.SelectSubset<T, PlayerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Players and returns the data updated in the database.
   * @param {PlayerUpdateManyAndReturnArgs} args - Arguments to update many Players.
   * @example
   * // Update many Players
   * const player = await prisma.player.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Players and only return the `id`
   * const playerWithIdOnly = await prisma.player.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlayerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlayerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Player.
   * @param {PlayerUpsertArgs} args - Arguments to update or create a Player.
   * @example
   * // Update or create a Player
   * const player = await prisma.player.upsert({
   *   create: {
   *     // ... data to create a Player
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Player we want to update
   *   }
   * })
   */
  upsert<T extends PlayerUpsertArgs>(args: Prisma.SelectSubset<T, PlayerUpsertArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Players.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerCountArgs} args - Arguments to filter Players to count.
   * @example
   * // Count the number of Players
   * const count = await prisma.player.count({
   *   where: {
   *     // ... the filter for the Players we want to count
   *   }
   * })
  **/
  count<T extends PlayerCountArgs>(
    args?: Prisma.Subset<T, PlayerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlayerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Player.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlayerAggregateArgs>(args: Prisma.Subset<T, PlayerAggregateArgs>): Prisma.PrismaPromise<GetPlayerAggregateType<T>>

  /**
   * Group by Player.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlayerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlayerGroupByArgs['orderBy'] }
      : { orderBy?: PlayerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlayerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlayerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Player model
 */
readonly fields: PlayerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Player.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlayerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.SessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SessionDefaultArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  randomAsP1<T extends Prisma.Player$randomAsP1Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Player$randomAsP1Args<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Transaction_RandomPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  randomAsP2<T extends Prisma.Player$randomAsP2Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Player$randomAsP2Args<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Transaction_RandomPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  randomAsP3<T extends Prisma.Player$randomAsP3Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Player$randomAsP3Args<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Transaction_RandomPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  randomAsP4<T extends Prisma.Player$randomAsP4Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Player$randomAsP4Args<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Transaction_RandomPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Player model
 */
export interface PlayerFieldRefs {
  readonly id: Prisma.FieldRef<"Player", 'String'>
  readonly sessionId: Prisma.FieldRef<"Player", 'String'>
  readonly name: Prisma.FieldRef<"Player", 'String'>
  readonly level: Prisma.FieldRef<"Player", 'String'>
  readonly isOnline: Prisma.FieldRef<"Player", 'Boolean'>
  readonly isPaid: Prisma.FieldRef<"Player", 'Boolean'>
  readonly isActive: Prisma.FieldRef<"Player", 'Boolean'>
  readonly isPlaying: Prisma.FieldRef<"Player", 'Boolean'>
  readonly playingSince: Prisma.FieldRef<"Player", 'DateTime'>
  readonly createdDate: Prisma.FieldRef<"Player", 'DateTime'>
  readonly createdBy: Prisma.FieldRef<"Player", 'String'>
  readonly updatedDate: Prisma.FieldRef<"Player", 'DateTime'>
  readonly updatedBy: Prisma.FieldRef<"Player", 'String'>
}
    

// Custom InputTypes
/**
 * Player findUnique
 */
export type PlayerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Player to fetch.
   */
  where: Prisma.PlayerWhereUniqueInput
}

/**
 * Player findUniqueOrThrow
 */
export type PlayerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Player to fetch.
   */
  where: Prisma.PlayerWhereUniqueInput
}

/**
 * Player findFirst
 */
export type PlayerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Player to fetch.
   */
  where?: Prisma.PlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Players to fetch.
   */
  orderBy?: Prisma.PlayerOrderByWithRelationInput | Prisma.PlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Players.
   */
  cursor?: Prisma.PlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Players from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Players.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Players.
   */
  distinct?: Prisma.PlayerScalarFieldEnum | Prisma.PlayerScalarFieldEnum[]
}

/**
 * Player findFirstOrThrow
 */
export type PlayerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Player to fetch.
   */
  where?: Prisma.PlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Players to fetch.
   */
  orderBy?: Prisma.PlayerOrderByWithRelationInput | Prisma.PlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Players.
   */
  cursor?: Prisma.PlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Players from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Players.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Players.
   */
  distinct?: Prisma.PlayerScalarFieldEnum | Prisma.PlayerScalarFieldEnum[]
}

/**
 * Player findMany
 */
export type PlayerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Players to fetch.
   */
  where?: Prisma.PlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Players to fetch.
   */
  orderBy?: Prisma.PlayerOrderByWithRelationInput | Prisma.PlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Players.
   */
  cursor?: Prisma.PlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Players from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Players.
   */
  skip?: number
  distinct?: Prisma.PlayerScalarFieldEnum | Prisma.PlayerScalarFieldEnum[]
}

/**
 * Player create
 */
export type PlayerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * The data needed to create a Player.
   */
  data: Prisma.XOR<Prisma.PlayerCreateInput, Prisma.PlayerUncheckedCreateInput>
}

/**
 * Player createMany
 */
export type PlayerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Players.
   */
  data: Prisma.PlayerCreateManyInput | Prisma.PlayerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Player createManyAndReturn
 */
export type PlayerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * The data used to create many Players.
   */
  data: Prisma.PlayerCreateManyInput | Prisma.PlayerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Player update
 */
export type PlayerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * The data needed to update a Player.
   */
  data: Prisma.XOR<Prisma.PlayerUpdateInput, Prisma.PlayerUncheckedUpdateInput>
  /**
   * Choose, which Player to update.
   */
  where: Prisma.PlayerWhereUniqueInput
}

/**
 * Player updateMany
 */
export type PlayerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Players.
   */
  data: Prisma.XOR<Prisma.PlayerUpdateManyMutationInput, Prisma.PlayerUncheckedUpdateManyInput>
  /**
   * Filter which Players to update
   */
  where?: Prisma.PlayerWhereInput
  /**
   * Limit how many Players to update.
   */
  limit?: number
}

/**
 * Player updateManyAndReturn
 */
export type PlayerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * The data used to update Players.
   */
  data: Prisma.XOR<Prisma.PlayerUpdateManyMutationInput, Prisma.PlayerUncheckedUpdateManyInput>
  /**
   * Filter which Players to update
   */
  where?: Prisma.PlayerWhereInput
  /**
   * Limit how many Players to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Player upsert
 */
export type PlayerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * The filter to search for the Player to update in case it exists.
   */
  where: Prisma.PlayerWhereUniqueInput
  /**
   * In case the Player found by the `where` argument doesn't exist, create a new Player with this data.
   */
  create: Prisma.XOR<Prisma.PlayerCreateInput, Prisma.PlayerUncheckedCreateInput>
  /**
   * In case the Player was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlayerUpdateInput, Prisma.PlayerUncheckedUpdateInput>
}

/**
 * Player delete
 */
export type PlayerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter which Player to delete.
   */
  where: Prisma.PlayerWhereUniqueInput
}

/**
 * Player deleteMany
 */
export type PlayerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Players to delete
   */
  where?: Prisma.PlayerWhereInput
  /**
   * Limit how many Players to delete.
   */
  limit?: number
}

/**
 * Player.randomAsP1
 */
export type Player$randomAsP1Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction_Random
   */
  select?: Prisma.Transaction_RandomSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction_Random
   */
  omit?: Prisma.Transaction_RandomOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Transaction_RandomInclude<ExtArgs> | null
  where?: Prisma.Transaction_RandomWhereInput
  orderBy?: Prisma.Transaction_RandomOrderByWithRelationInput | Prisma.Transaction_RandomOrderByWithRelationInput[]
  cursor?: Prisma.Transaction_RandomWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Transaction_RandomScalarFieldEnum | Prisma.Transaction_RandomScalarFieldEnum[]
}

/**
 * Player.randomAsP2
 */
export type Player$randomAsP2Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction_Random
   */
  select?: Prisma.Transaction_RandomSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction_Random
   */
  omit?: Prisma.Transaction_RandomOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Transaction_RandomInclude<ExtArgs> | null
  where?: Prisma.Transaction_RandomWhereInput
  orderBy?: Prisma.Transaction_RandomOrderByWithRelationInput | Prisma.Transaction_RandomOrderByWithRelationInput[]
  cursor?: Prisma.Transaction_RandomWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Transaction_RandomScalarFieldEnum | Prisma.Transaction_RandomScalarFieldEnum[]
}

/**
 * Player.randomAsP3
 */
export type Player$randomAsP3Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction_Random
   */
  select?: Prisma.Transaction_RandomSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction_Random
   */
  omit?: Prisma.Transaction_RandomOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Transaction_RandomInclude<ExtArgs> | null
  where?: Prisma.Transaction_RandomWhereInput
  orderBy?: Prisma.Transaction_RandomOrderByWithRelationInput | Prisma.Transaction_RandomOrderByWithRelationInput[]
  cursor?: Prisma.Transaction_RandomWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Transaction_RandomScalarFieldEnum | Prisma.Transaction_RandomScalarFieldEnum[]
}

/**
 * Player.randomAsP4
 */
export type Player$randomAsP4Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction_Random
   */
  select?: Prisma.Transaction_RandomSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction_Random
   */
  omit?: Prisma.Transaction_RandomOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Transaction_RandomInclude<ExtArgs> | null
  where?: Prisma.Transaction_RandomWhereInput
  orderBy?: Prisma.Transaction_RandomOrderByWithRelationInput | Prisma.Transaction_RandomOrderByWithRelationInput[]
  cursor?: Prisma.Transaction_RandomWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Transaction_RandomScalarFieldEnum | Prisma.Transaction_RandomScalarFieldEnum[]
}

/**
 * Player without action
 */
export type PlayerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
}
